import { NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'

export async function POST(req: Request) {
  try {
    const data = await req.json()
    const { name, phone, email, deliveryInfo, message, items, total, honeypot } = data

    if (!name || !phone || !items || !items.length) {
      return NextResponse.json({ error: 'Будь ласка, заповніть усі обов’язкові поля' }, { status: 400 })
    }

    const payload = await getPayload({ config })

    // Build data object, carefully omitting empty email to avoid CMS validation errors
    const orderData: any = {
      name,
      phone,
      deliveryInfo,
      message: message || '',
      items,
      total: Number(total),
      status: 'new',
      source: 'checkout',
      honeypot,
    }

    if (email && email.trim() !== '') {
      orderData.email = email.trim()
    }

    // Create the order in Payload CMS (orderNumber is generated by beforeChange hook)
    const order = await payload.create({
      collection: 'orders',
      data: orderData,
      req, // Pass the Next.js request object for hooks to access headers
    })

    return NextResponse.json({ success: true, orderId: order.id, orderNumber: (order as any).orderNumber }, { status: 201 })
  } catch (err: any) {
    console.error('Checkout error:', err)
    return NextResponse.json(
      { error: err.message || 'Не вдалося оформити замовлення. Спробуйте пізніше.' },
      { status: 500 }
    )
  }
}
